version: "2" # rpi lags a bit behind

services:
  app:
    depends_on: 
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "1337:80"
    environment: 
      - PARTKEEPR_DATABASE_HOST
      - PARTKEEPR_DATABASE_NAME
      - PARTKEEPR_DATABASE_PORT
      - PARTKEEPR_DATABASE_USER
      - PARTKEEPR_DATABASE_PASS

  database:
    # image: linuxserver/mariadb # for use on raspberry pi 3 or 4
    image: mariadb:10.0 # intel/amd
    restart: on-failure
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=partkeepr
      - MYSQL_USER=partkeepr
      - MYSQL_PASSWORD=partkeepr